version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: survey-app
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql_db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start:prod
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge